ne mergáld be csak így egyszerűbb megmutatni
kadam03/purr-game pull request #1
Opened 2024-09-23 22:45 UTC by GuBee33

2024-09-26 20:51 UTC, kadam03 commented
@GuBee33 amúgy itt voltak a kommentek a conversation alatt

2024-09-27 08:51 UTC, GuBee33 commented
@kadam03 ezt az üzeneted látom de semmi mást

2024-09-27 12:38 UTC, robipanczel commented
Én is látom 😮

2024-10-01 10:45 UTC, kadam03 requested changes

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Asset/Image/Cats/Img_VoidCat2.png
Nem tudtam pontosan scripthez írni, ez a cica néha saját magába mergelődik, aztán pedig a kettővel nagyobb labdába

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/new_cica.gd
> +	collision_shape.shape = collision_shape.shape.duplicate()
It van egy ilyen errorunk játék közben:
E 0:01:27:0715   new_cica.gd:20 @ _ready(): Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>    Condition "body->get_space() && flushing_queries" is true.
  <C++ Source>   servers/physics_2d/godot_physics_server_2d.cpp:663 @ body_set_shape_as_one_way_collision()
  <Stack Trace>  new_cica.gd:20 @ _ready()
                 new_cica.gd:60 @ _on_Ball_collided()

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/new_cica.gd
Egy ilyen error a collision signalra játék közben:
E 0:01:28:0264   emit_signalp: Error calling from signal 'body_entered' to callable: 'RigidBody2D(new_cica.gd)::_on_Ball_collided': Cannot convert argument 1 from Object to Object.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/game_area.gd
> +		# Start the cooldown timer after kiscica is added
🤣😺

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/new_cica.gd
> +	if Engine.is_editor_hint():
mivel nincs már editorban lévő származtatott cica mert kiPURRgáltad őket, nincs mit nézni a viewportban, és így ezek sem kellenek

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/new_cica.gd
> +	collision_shape.shape = collision_shape.shape.duplicate()
valamit ezzel a collisionnel okoskodni kell mert ez ratyinak tűnik, de ötletem még nincs (igen, tudom h ez a sor tőlem és a chatGPT-től jött)

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Asset/Image/Cats/ca1.png
és a T? :D

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/cat_or_ball.gd
> +		update_ball_properties(self.current_id,self.current_type)
Ez csak akkor kell, ha editorban is látni akarjuk az összekattintott labdákat

2024-10-01 10:45 UTC, kadam03 commented on furballFusion/Script/cat_or_ball.gd
> +	if  ball is RigidBody2D and ball.current_type == "ball" and self.current_type == "cat" and ball.is_in_group(str(current_id)) and current_id < number_of_textures-1:
valami fixen nem jó, mert a sárga cica vegyül a fehér manccsal. Ez intended? Ézért lettek megkülönböztetve a labdák és a macskák?

2024-10-01 23:02 UTC, kadam03 approved these changes

2024-10-01 23:02 UTC, kadam03 commented on furballFusion/Script/game_area.gd
> +const COOLDOWN =0.15
The cooldown can be still bigger because I can hit the falling objects with the next object if I tap it too fast

2024-10-01 23:02 UTC, kadam03 commented on furballFusion/Script/game_area.gd
> +			#ball.position = Vector2(get_viewport().get_mouse_position().x, lim_left.position.y)
I think you can remove this comment

2024-10-01 23:02 UTC, kadam03 commented on furballFusion/Script/cat_or_ball.gd
> +	if Global.animated_sprites_sized_and_collision==null:
Ez a global dolog hogy létezik? nem találtam hová van csatolva, hogy van beleoktrojálva az egész flowba, hogy ez elérhető legyen

2024-10-01 23:07 UTC, merged